# Generated by Django 6.0.1 on 2026-01-07 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate_heart', models.BooleanField(default=False)),
                ('donate_kidneys', models.BooleanField(default=False)),
                ('donate_liver', models.BooleanField(default=False)),
                ('donate_eyes', models.BooleanField(default=False)),
                ('donate_lungs', models.BooleanField(default=False)),
                ('donate_pancreas', models.BooleanField(default=False)),
                ('pledge_date', models.DateTimeField(auto_now_add=True)),
                ('donor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.donor')),
            ],
        ),
    ]
