# Generated by Django 6.0 on 2026-03-21 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_achievement_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='slot_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HospitalBloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=5)),
                ('is_emergency', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.hospital')),
            ],
        ),
    ]
