# Generated by Django 6.0 on 2026-03-31 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_donationrequest_slot_date_hospitalbloodrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='donation_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
